
DECLARE @MyVar DATETIME = GETDATE()
SELECT @MyVar


DECLARE @myString VARCHAR(64);
SELECT @myString = 'MY EXAMPLE';
SELECT ' BELOW CHARACTERS AND THEIR POSITION IN GIVEN STRING' AS 'MY EXAMPLE',
CHARINDEX('Y' , @myString) AS 'Y',
CHARINDEX('X' , @myString) AS 'X',
CHARINDEX('LE' , @myString) AS 'LE';


SELECT CONCAT ('SARTHAK' , ' - ' ,'WALAKE') AS FULLNAME;
SELECT LEFT('SARTHAK WALAKE' , 3);		-- SELECT 3 CHARACTER FROM LEFT
SELECT LEN('SARTHAK WALAKE');			-- STRING LENGTH


DECLARE @myString VARCHAR(250);
SET @myString = 'sarthak laxman walake';
SELECT UPPER(@myString);


-- If Else
DECLARE @X INT
SET @X = 9
IF @X = 9 PRINT 'THE NUMBER IS '+CAST(@X AS VARCHAR(10))
ELSE PRINT 'THE NUMBER IS NOT 29'


-- WHILE LOOP
DECLARE @VALUE INT;
SET @VALUE = 0;
WHILE @VALUE <= 10
BEGIN 
	PRINT 'CURRENT VALUE IN WHILE LOOP : '+CAST(@VALUE AS VARCHAR(10))
	SET @VALUE = @VALUE + 1;
END;
PRINT 'DONE WHILE LOOP';


-- WHILE LOOP WITH BREAK
DECLARE @INTFLAG INT
SET @INTFLAG = 1
WHILE(@INTFLAG <= 5)
BEGIN
PRINT @INTFLAG
SET @INTFLAG = @INTFLAG + 1
IF @INTFLAG = 4
BREAK;


-- WHILE LOOP WITH CONTINUE AND BREAK
DECLARE @myVal INT
SET @myVal = 1
WHILE (@myVal <= 5)
BEGIN 
PRINT @myVal
SET @myVal = @myVal + 1
CONTINUE;
IF @myVal = 4		-- THIS WILL NEVER GET EXECUTED
BREAK;
END


-- SELECT CASE 
DECLARE @intInput INT
SET @intInput = 2
SELECT CASE(@intInput)
WHEN 1 THEN 'ONE'
WHEN 2 THEN 'TWO'
WHEN 3 THEN 'THREE'
ELSE 'YOUR MESSAAGE.'
END


-- TSQL CODE
DECLARE @N TINYINT
SET @N = 5
IF(@N BETWEEN 4 AND 6)
BEGIN 
  WHILE(@N > 0)
    BEGIN
	SELECT @N AS 'NUMBER' , CASE
		WHEN(@N % 2) = 0
		THEN 'EVEN'
		ELSE 'ODD'
		END AS 'TYPE'
		SET @N = @N - 1
	END
  END
 ELSE
PRINT 'NO ANALYSIS'